baseURL = "https://hs-autoservice.de/"
languageCode = "de-de"
paginate = 6
theme = "portio"
title = "HS-Autoserivce"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Über uns"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3

# Sitemap Menu
[[menu.sitemap]]
name = "Über uns"
url = "#"
weight = 1
[[menu.sitemap]]
name = "Kontakt"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Impressum"
url = "#"
weight = 3

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Alle Rechte vorbehalten copyright © HS-Autoservice 2022"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Dieselstr. 10, 73734 Esslingen"
email = "anfrage@hs-autoservice.de"
openingHours = "Mo-Fr 09:00 bis 18:00 Uhr"
phone = "+49 160 98707999"
phone2 = "+49 175 64295454"


[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
